- name: update system
  yum: name=* state=latest
  become: yes

- name: install other dev tools
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - cmake
    - gcc-c++
    - python3-devel
    - python2-devel
    - mercurial
    - screen
    - make
    - vim
    - golang
    - ntp
    - git
    - wget
    - ncurses-term
    - npm
    - dnf-plugins-core
    - python3-libselinux
    - python2-libselinux
    - python
  become: yes

- name: disable selinux
  selinux: state=disabled
  become: yes

- name: disable of selinux - now
  command: setenforce 0
  become: yes
  ignore_errors: True


- name: remove all old docker
  yum:
    name:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-logrotate
    - docker-engine
    state: removed
    disable_gpg_check: yes
  become: yes

- name: install docker ce dnf repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: yes

- name: install docker ce
  yum: name=docker-ce state=present disable_gpg_check=yes
  become: yes

- name: enable services
  service: name={{ item }} state=started enabled=yes
  become: yes
  with_items:
    - docker
    - ntpd

- name: copy screenrc
  copy: src=screenrc dest=/home/vagrant/.screenrc force=no

- name: copy .bashrc
  copy: src=bashrc dest=/home/vagrant/.bashrc force=yes

- name: copy vimrc
  copy: src=vimrc dest=/home/vagrant/.vimrc force=no

- name: copy gitconfig
  copy: src={{ lookup('env','HOME') }}/.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=0600 force=no

- name: get vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim

- name: create gopath directory
  file: path=/home/vagrant/git/golang state=directory

