
export GOPATH=$HOME/git/go
export PATH=$PATH:$GOPATH/bin
export EDITOR=vim
alias cdp='cd $GOPATH/src/github.com/pblcache/pblcache'

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

